version: "3.8"
name: app-bank-ppdb
services:
    bank-ppdb-app:
        build:
            context: .
            dockerfile: Dockerfile
        image: bank-ppdb-image-app
        container_name: bank-ppdb-app-container
        tty: true
        # env_file: ../.env
        restart: unless-stopped
        # ports:
        #    - '6006:3000'
        volumes:
            - app-bank-ppdb-volume:/var/www/public
        networks:
            - app-network-bank-ppdb

    web-server-bank-ppdb:
        image: nginx:1.23.3
        container_name: web-server-bank-ppdb-container
        restart: unless-stopped
        ports:
            - "7008:80"
        volumes:
            - app-bank-ppdb-volume:/var/www/public
            - ./nginx/conf.d:/etc/nginx/conf.d
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
        depends_on:
            - bank-ppdb-app
        networks:
            - app-network-bank-ppdb

networks:
    app-network-bank-ppdb:
        driver: bridge

volumes:
    app-bank-ppdb-volume:
